19 - Update (README.md): added instruction to install lombok
plansoft-it/GestioneOrari pull request #22
Opened 2020-06-08 14:05 UTC by antoniocaia

Closes #19

2020-06-08 15:54 UTC, Wabri requested changes
Qualche piccola modifica per aumentare l'ordine e la leggibilità

2020-06-08 15:54 UTC, Wabri commented on README.md
> +#### IDEE Eclipse, OS Linux:
```suggestion
### Lombok

Utilizzata per ridurre le righe di codice per metodi e costruttori, vedi [sito Lombok](https://projectlombok.org/).

#### Installazione in ambiente Linux
```

2020-06-08 15:54 UTC, Wabri commented on README.md
> +2. Rendere *lombok.jar* eseguibile con il comando `chmod +x path/to/lombok.jar`
Si può evitare questo passaggio unendo il punto subito dopo usando questo comando:
```bash
java -jar lombok.jar
```
Così però mi piace un po' di più che forza magari una nuova conoscenza della system call chmod.

2020-06-08 15:54 UTC, Wabri commented on README.md
> +3. Eseguire *lombok.jar*.
```suggestion
3. Eseguire *lombok.jar*:
```

2020-06-08 15:54 UTC, Wabri commented on README.md
> +## Installare [ Lombok](https://projectlombok.org/)
```suggestion
## Develop 

Dipendenze Java: 
- [Lombok](#lombok)

```

2020-06-08 15:54 UTC, Wabri commented on README.md
> +#### IDEE Eclipse, OS Windows:
```suggestion
#### Installazione in ambiente Windows
```

2020-06-08 15:54 UTC, Wabri commented on README.md
> +#### Cosa fare se dopo l'installazione Eclipse non si dovesse aprire:
```suggestion
#### Cosa fare se dopo l'installazione Eclipse non si dovesse aprire

```

2020-06-09 06:50 UTC, Wabri approved these changes

2020-06-17 12:55 UTC, scrivereleonardo approved these changes

2020-06-17 15:06 UTC, merged