Rework/24/processed
plansoft-it/GestioneOrari pull request #25
Opened 2020-06-13 10:19 UTC by antoniocaia

Lo scopo di queste modifiche è quello di aumentare la modularità e seguire il principio di singola responsabilità , separando il parse del file da le operazione eseguite sui dati.

2020-06-15 08:44 UTC, Wabri commented on GestioneOrari/src/GestioneOrari.java
> +	public static void main(String[] args) throws ParseException, IOException {
Il main non deve lanciare eccezioni, dovresti usare il try catch per il metodo che lancia questi errori

2020-06-15 08:45 UTC, Wabri commented on GestioneOrari/src/processed/ProcessedFile.java
> +	private @Getter float totalWorkOurs;
Typo

2020-06-19 15:49 UTC, MariusLovesPizza commented
Domanda, i conflitti devono essere risolti ?

2020-06-19 17:58 UTC, antoniocaia commented
> Domanda, i conflitti devono essere risolti ?

Penso sia meglio aspettare le revisioni (e apportare le eventuali modifiche), e quando viene dato il via libera al merge allora si risolvono i conflitti.

2020-06-20 09:04 UTC, MariusLovesPizza commented
> 
> 
> > Domanda, i conflitti devono essere risolti ?
> 
> Penso sia meglio aspettare le revisioni (e apportare le eventuali modifiche), e quando viene dato il via libera al merge allora si risolvono i conflitti.

Quindi la sequenza è: revisionare, approvare, risoluzione conflitti, merge, delete branch

2020-06-22 07:45 UTC, Wabri commented
Non c'è una sequenza prestabilita. Di norma si fa la review quando lo sviluppatore toglie la pull request dal work in progress e di norma rimane in work in progress fintanto che le implementazioni non vengono completate e i conflitti risolti. Indipendentemente da questo la review la puoi fare sempre anche per aiutare l'altro sviluppatore. Usciti dalla wip (work in progress) si passa in code review, che può sia rimandare lo sviluppatore a cui è assegnata la pull request nuovamente in sviluppo perchè richieste delle modifiche oppure approvata e quindi dare la possibilità di effettuare la merge. Solo dopo che la merge viene completata si elimina il branch. ( @scrivereleonardo serve anche a te )

2020-06-22 10:04 UTC, MariusLovesPizza commented
> 
> 
> Non c'è una sequenza prestabilita. Di norma si fa la review quando lo sviluppatore toglie la pull request dal work in progress e di norma rimane in work in progress fintanto che le implementazioni non vengono completate e i conflitti risolti. Indipendentemente da questo la review la puoi fare sempre anche per aiutare l'altro sviluppatore. Usciti dalla wip (work in progress) si passa in code review, che può sia rimandare lo sviluppatore a cui è assegnata la pull request nuovamente in sviluppo perchè richieste delle modifiche oppure approvata e quindi dare la possibilità di effettuare la merge. Solo dopo che la merge viene completata si elimina il branch. ( @scrivereleonardo serve anche a te )

Ottima spiegazione. Bravo e grazie. 
Dove si vede che e' ancora in WiP oppure capire quando le implementazioni sono completate?

2020-06-22 10:47 UTC, Wabri commented
> Dove si vede che e' ancora in WiP oppure capire quando le implementazioni sono completate?

Ci sono diversi modi per vedere che è in wip:

- Se ci sono dei conflitti da risolvere
- Se è dichiaratamente indicato in wip, da poco github ha inserito una feature che permette di segnare come bozza la pr:
![2020-06-22-12-43-34_345x229](https://user-images.githubusercontent.com/12409541/85279222-5ac99880-b486-11ea-8177-f658d8aef082.png)
- Se non sono richiesti reviewers

2020-06-22 11:50 UTC, MariusLovesPizza commented
> 
> 
> > Dove si vede che e' ancora in WiP oppure capire quando le implementazioni sono completate?
> 
> Ci sono diversi modi per vedere che è in wip:
> 
>     * Se ci sono dei conflitti da risolvere
> 
>     * Se è dichiaratamente indicato in wip, da poco github ha inserito una feature che permette di segnare come bozza la pr:
>       ![2020-06-22-12-43-34_345x229](https://user-images.githubusercontent.com/12409541/85279222-5ac99880-b486-11ea-8177-f658d8aef082.png)
> 
>     * Se non sono richiesti reviewers

Good
Bene, questa linea l'avevo vista.

2020-06-22 13:57 UTC, antoniocaia commented
> Non c'è una sequenza prestabilita. Di norma si fa la review quando lo sviluppatore toglie la pull request dal work in progress e di norma rimane in work in progress fintanto che le implementazioni non vengono completate e i conflitti risolti. Indipendentemente da questo la review la puoi fare sempre anche per aiutare l'altro sviluppatore. Usciti dalla wip (work in progress) si passa in code review, che può sia rimandare lo sviluppatore a cui è assegnata la pull request nuovamente in sviluppo perchè richieste delle modifiche oppure approvata e quindi dare la possibilità di effettuare la merge. Solo dopo che la merge viene completata si elimina il branch. ( @scrivereleonardo serve anche a te )

Grazie mille per la spiegazione, specialmente la parte dopo riguardo al wip.

2020-06-22 15:55 UTC, antoniocaia commented
Quando hai un po' di tempo @Wabri potresti dare uno sguardo al codice? Anche solo per sapere se hanno senso i cambiamenti che propongo o se conviene prendere un'altra strada.

2020-06-23 17:13 UTC, Wabri requested changes
Con questo refactoring il codice sembra più pulito e meno difficile da comprendere. 

Ottima gestione delle mappe e utilizzo dei costrutti.

PS: Avrei dovuto leggere prima i test, ma non li avevo visti quindi ho revisionato e commentato per ora solo le classi non test. Avevo pensato di provare a fare TDD una volta che si riesce a entrare in carreggiata con il progetto, ricordati di documentare le librerie che usi nel readme. Per ora dobbiamo fare così fintanto che non trasformiamo il progetto in maven.

2020-06-23 17:13 UTC, Wabri commented on .gitignore
> +bin/
Alla fine di ogni file ci dovrebbe essere sempre EOF (end of file)  altrimenti non ci sono modi per capire se il file è concluso o no, nel 2020 non ci sono problemi però è teoricamente più corretto.

2020-06-23 17:13 UTC, Wabri commented on src/GestioneOrari.java
> +}
Stessa cosa del gitignore commentato sopra

2020-06-23 17:13 UTC, Wabri commented on src/parser/FormatChecker.java
> +		if (date.matches("(20[2-9][0-9])-([1-9]|0[1-9]|1[0-2])-([0-2][0-9]|3[0-1]|[1-9])"))
Cerca sempre di mettere le parentesi anche se c'è solo una sola istruzione. Serve a prevedere errori di scrittura.

2020-06-23 17:13 UTC, Wabri commented on src/parser/FormatChecker.java
> +		if (time.matches("(0[0-9]|1[0-9]|2[0-3]|[0-9]):([0-5][0-9]|[0-9])"))
Stessa cosa dell'if del checkDate

2020-06-23 17:13 UTC, Wabri commented on src/parser/FormatChecker.java
> +		if (!start.isBefore(end))
Stessa cosa dell'if di checkTimeCustomFormat

2020-06-23 17:13 UTC, Wabri commented on src/parser/FormatChecker.java
> +}
Stessa cosa della classe GestioneOrari commentato sopra

2020-06-23 17:13 UTC, Wabri commented on src/parser/Parser.java
> +}
EOF

2020-06-23 17:13 UTC, Wabri commented on src/parser/Parser.java
> +				Date date = FormatChecker.checkDate(subStrings[0]);
Questo ci voleva, non era compito di questa classe controllare il formato della data.

2020-06-23 17:13 UTC, Wabri commented on src/parser/Parser.java
> +				Row tmp = new Row(date, startHour, endHour, order, note);
Sarebbe meglio dargli un nome più significativo nonostante questo oggetto non abbia molti compiti

2020-06-23 17:13 UTC, Wabri commented on src/parser/Parser.java
> +		} catch (ParseException | DateTimeParseException e) {
Attento a usare le condizioni sui tipi, rimane una good practice per evitare la duplicazione. @scrivereleonardo @MariusLovesPizza questa è una gestione del catch "avanzata" serve per evitare i try catch multipli rendendo il codice più leggibile e pulito.

2020-06-23 17:13 UTC, Wabri commented on src/processed/ProcessedFile.java
> +		for (Row row : rows) {
@MariusLovesPizza @scrivereleonardo Questo costrutto si chiama **for each** anche questo permette di rendere il codice più pulito e leggero.

2020-06-23 17:13 UTC, Wabri commented on src/processed/ProcessedFile.java
> +}
Ma non te li mette eclipse gli EOF?

2020-06-23 17:13 UTC, Wabri commented on src/row/Row.java
> +}
EOF

2020-06-23 17:59 UTC, MariusLovesPizza commented on src/parser/Parser.java
> +		} catch (ParseException | DateTimeParseException e) {
Si, anche a me piace di più usare un solo catch

> 
> 
> Attento a usare le condizioni sui tipi, rimane una good practice per evitare la duplicazione. @scrivereleonardo @MariusLovesPizza questa è una gestione del catch "avanzata" serve per evitare i try catch multipli rendendo il codice più leggibile e pulito.

Si, anche a me piace usare più questa versione di catch :D

2020-06-25 11:09 UTC, antoniocaia commented on src/parser/Parser.java
> +		} catch (ParseException | DateTimeParseException e) {
Dovrei aver risolto (avevo dimenticato di catturare una eccezione), anche se non sono sicuro al 100% che fosse quello a cui ti riferivi

2020-06-25 11:11 UTC, antoniocaia commented on src/processed/ProcessedFile.java
> +}
E' più probabile li abbia tolti io inavvertitamente :)

2020-06-25 11:16 UTC, antoniocaia commented
> Con questo refactoring il codice sembra più pulito e meno difficile da comprendere.
> 
> Ottima gestione delle mappe e utilizzo dei costrutti.
> 
> PS: Avrei dovuto leggere prima i test, ma non li avevo visti quindi ho revisionato e commentato per ora solo le classi non test. Avevo pensato di provare a fare TDD una volta che si riesce a entrare in carreggiata con il progetto, ricordati di documentare le librerie che usi nel readme. Per ora dobbiamo fare così fintanto che non trasformiamo il progetto in maven.

Ammetto che i miei test rappresentano più un tentativo di test che test veri e propri... la teoria mi è abbastanza chiara ma metterla in pratica è un po' più dura. Quando riesco aggiorno il readme, ho usato mochito e assertj.

2020-06-25 11:17 UTC, antoniocaia commented
> > Con questo refactoring il codice sembra più pulito e meno difficile da comprendere.
> > Ottima gestione delle mappe e utilizzo dei costrutti.
> > PS: Avrei dovuto leggere prima i test, ma non li avevo visti quindi ho revisionato e commentato per ora solo le classi non test. Avevo pensato di provare a fare TDD una volta che si riesce a entrare in carreggiata con il progetto, ricordati di documentare le librerie che usi nel readme. Per ora dobbiamo fare così fintanto che non trasformiamo il progetto in maven.
> 
> Ammetto che i miei test rappresentano più un tentativo di test che test veri e propri... la teoria mi è abbastanza chiara ma metterla in pratica è un po' più dura. Quando riesco aggiorno il readme, ho usato mochito e assertj.

Una domanda: quanto è sbagliato definire getters da usare solo per i test?

2020-06-25 16:04 UTC, Wabri commented
> Una domanda: quanto è sbagliato definire getters da usare solo per i test?

Non è sbagliatissimo, i getters e setters li usi sempre. Diciamo che i test servono per coprire funzionalità non per crearne di nuove.

2020-06-26 09:21 UTC, Wabri submitted a review, later dismissed

2020-06-26 09:21 UTC, Wabri commented on README.md
> +7. Spostare  il *lombok.jar* nella cartella *lib* del progetto in cui vogliamo installare la dipendenza (Drag and Drop nell'IDEE, navigando nel filesystem, ... )
```suggestion
4. Spostare  il *lombok.jar* nella cartella *lib* del progetto in cui vogliamo installare la dipendenza (Drag and Drop nell'IDEE, navigando nel filesystem, ... )
```

2020-06-26 09:21 UTC, Wabri commented on README.md
>  8. Nell'IDEE selezionare nuovamente il progetto,  premere **F5** sulla propria tastiera oppure `Rigth Click -> Refresh`
```suggestion
5. Nell'IDEE selezionare nuovamente il progetto,  premere **F5** sulla propria tastiera oppure `Rigth Click -> Refresh`
```

2020-06-26 09:21 UTC, Wabri commented on README.md
>  9. Nella cartella *lib* dovrebbe essere comparso il *lombok.jar*. Selezionarlo e `Rigth Click -> Build Path -> Add to Build Path`
```suggestion
6. Nella cartella *lib* dovrebbe essere comparso il *lombok.jar*. Selezionarlo e `Rigth Click -> Build Path -> Add to Build Path`
```

2020-06-26 09:21 UTC, Wabri commented on README.md
>  10. Chiudere e riaprire l'IDEE.
```suggestion
7. Chiudere e riaprire l'IDEE.
```

2020-06-26 09:24 UTC, merged