41 - Chore (MANIFEST): aggiunto MANIFEST.MF e documentazione
plansoft-it/GestioneOrari pull request #47
Opened 2020-06-29 13:20 UTC by antoniocaia

Closes #41

2020-07-02 12:00 UTC, Wabri requested changes

2020-07-02 12:00 UTC, Wabri commented on README.md
> +- Se non si hanno a disposizione i binari, e necessario posizionarsi nella cartella con i sorgenti ed eseguire i seguenti comandi:
```suggestion
- Se non si hanno a disposizione i binari, è necessario posizionarsi nella cartella con i sorgenti ed eseguire i seguenti comandi:
```

2020-07-02 12:00 UTC, Wabri commented on README.md
> +
```suggestion

Una volta generato l'eseguibile GO.jar è possibile rimuovere i file compilati.

```

2020-07-03 12:36 UTC, Wabri approved these changes

2020-07-04 18:05 UTC, scrivereleonardo approved these changes

2020-07-08 13:11 UTC, merged